"""initial schema Sika

Revision ID: ed064bb12f6e
Revises: 
Create Date: 2026-09-06 17:24:33.499943

"""
from alembic import op
import sqlalchemy as sa


revision = 'ed064bb12f6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comptes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prenom', sa.String(length=80), nullable=False),
    sa.Column('telephone', sa.String(length=32), nullable=False),
    sa.Column('langue', sa.String(length=8), nullable=False),
    sa.Column('devise', sa.String(length=8), nullable=False),
    sa.Column('pin_hash', sa.String(length=140), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telephone')
    )
    op.create_table('consentements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('compte_id', sa.String(length=36), nullable=False),
    sa.Column('perimetre', sa.String(length=60), nullable=False),
    sa.Column('canal', sa.String(length=30), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consentements_compte_id'), 'consentements', ['compte_id'], unique=False)
    op.create_table('dossiers_credit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('compte_id', sa.String(length=36), nullable=False),
    sa.Column('debut_periode', sa.Date(), nullable=False),
    sa.Column('fin_periode', sa.Date(), nullable=False),
    sa.Column('genere_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('contenu_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossiers_credit_compte_id'), 'dossiers_credit', ['compte_id'], unique=False)
    op.create_table('entrees_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('compte_id', sa.String(length=36), nullable=True),
    sa.Column('acteur', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('horodatage', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('compte_id', sa.String(length=36), nullable=False),
    sa.Column('destinataire', sa.String(length=32), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('statut', sa.String(length=12), nullable=False),
    sa.Column('tentatives', sa.Integer(), nullable=False),
    sa.Column('horodatage', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_compte_statut', 'notifications', ['compte_id', 'statut'], unique=False)
    op.create_table('objectifs_epargne',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('compte_id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('cible_cents', sa.BigInteger(), nullable=False),
    sa.Column('regle_montant_cents', sa.BigInteger(), nullable=True),
    sa.Column('regle_frequence', sa.String(length=30), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objectifs_epargne_compte_id'), 'objectifs_epargne', ['compte_id'], unique=False)
    op.create_table('produits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('compte_id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('prix_unitaire_cents', sa.BigInteger(), nullable=False),
    sa.Column('unite', sa.String(length=40), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produits_compte_id'), 'produits', ['compte_id'], unique=False)
    op.create_table('sessions_vocales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('compte_id', sa.String(length=36), nullable=True),
    sa.Column('session_aai_id', sa.String(length=80), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('langue', sa.String(length=8), nullable=False),
    sa.Column('debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_aai_id')
    )
    op.create_index('ix_sessions_compte_debut', 'sessions_vocales', ['compte_id', 'debut'], unique=False)
    op.create_table('tiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('compte_id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiers_compte_id'), 'tiers', ['compte_id'], unique=False)
    op.create_table('ecritures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('compte_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=12), nullable=False),
    sa.Column('montant_cents', sa.BigInteger(), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('tiers_id', sa.String(length=36), nullable=True),
    sa.Column('annule_par_id', sa.String(length=36), nullable=True),
    sa.Column('lignes_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['annule_par_id'], ['ecritures.id'], ),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes.id'], ),
    sa.ForeignKeyConstraint(['tiers_id'], ['tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ecritures_compte_date', 'ecritures', ['compte_id', 'date'], unique=False)
    op.create_table('dettes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('compte_id', sa.String(length=36), nullable=False),
    sa.Column('tiers_id', sa.String(length=36), nullable=False),
    sa.Column('ecriture_id', sa.String(length=36), nullable=True),
    sa.Column('sens', sa.String(length=20), nullable=False),
    sa.Column('montant_initial_cents', sa.BigInteger(), nullable=False),
    sa.Column('reste_du_cents', sa.BigInteger(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('echeance', sa.Date(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes.id'], ),
    sa.ForeignKeyConstraint(['ecriture_id'], ['ecritures.id'], ),
    sa.ForeignKeyConstraint(['tiers_id'], ['tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dettes_compte_statut', 'dettes', ['compte_id', 'statut'], unique=False)
    op.create_table('relances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('compte_id', sa.String(length=36), nullable=False),
    sa.Column('dette_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=12), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes.id'], ),
    sa.ForeignKeyConstraint(['dette_id'], ['dettes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relances_compte_id'), 'relances', ['compte_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relances_compte_id'), table_name='relances')
    op.drop_table('relances')
    op.drop_index('ix_dettes_compte_statut', table_name='dettes')
    op.drop_table('dettes')
    op.drop_index('ix_ecritures_compte_date', table_name='ecritures')
    op.drop_table('ecritures')
    op.drop_index(op.f('ix_tiers_compte_id'), table_name='tiers')
    op.drop_table('tiers')
    op.drop_index('ix_sessions_compte_debut', table_name='sessions_vocales')
    op.drop_table('sessions_vocales')
    op.drop_index(op.f('ix_produits_compte_id'), table_name='produits')
    op.drop_table('produits')
    op.drop_index(op.f('ix_objectifs_epargne_compte_id'), table_name='objectifs_epargne')
    op.drop_table('objectifs_epargne')
    op.drop_index('ix_notif_compte_statut', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('entrees_audit')
    op.drop_index(op.f('ix_dossiers_credit_compte_id'), table_name='dossiers_credit')
    op.drop_table('dossiers_credit')
    op.drop_index(op.f('ix_consentements_compte_id'), table_name='consentements')
    op.drop_table('consentements')
    op.drop_table('comptes')
    # ### end Alembic commands ###
